spring:
  data:
    elasticsearch:
      clusterName: cloud-crm
      clusterNodes: 10.10.10.128:9200
      username: elastic
      password: AWM2cmEdjJXgLkbD
  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
  datasource:
    url: jdbc:mysql://192.168.110.129:3306/onion?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    tomcat:
      max-active: 8
      max-idle: 4
      min-idle: 1
      test-on-borrow: true
      validation-query: select 1
      time-between-eviction-runs-millis: 360000
      initial-size: 5
    driver-class-name: com.mysql.jdbc.Driver