spring:
  data:
    elasticsearch:
      clusterName: cloud-crm
      clusterNodes: 10.10.10.128:9200
      username: elastic
      password: AWM2cmEdjJXgLkbD
#    jpa:
#      repositories:
#        enabled: true
  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
      url: jdbc:mysql://192.168.110.128:3306/onion?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: Root&2019
    tomcat:
      max-active: 8
      max-idle: 4
      min-idle: 1
      test-on-borrow: true
      validation-query: select 1
      time-between-eviction-runs-millis: 360000
      initial-size: 5
    driver-class-name: com.mysql.jdbc.Driver


